
name = "DashReactJsonSchemaForm"
uuid = "1b08a953-4be3-4667-9a23-3adc8484a434"
authors = ["Jillian Rowe <jillian@dabbleofdevops.com>"]
version = "0.1.6"

[deps]
Dash = "1b08a953-4be3-4667-9a23-3db579824955"

[compat]
julia = "1.2"
Dash = "0.1.3, 1.0"
